# List of the 100 companies int FTSE100 to test index scraping.

companies = [{'ticker' : 'AAL.L', 'company' : 'Anglo American PLC'},
{'ticker' : 'ABF.L', 'company' : 'Associated British Foods PLC'},
{'ticker' : 'ADM.L', 'company' : 'Admiral Group PLC'},
{'ticker' : 'ADN.L', 'company' : 'Aberdeen Asset Management PLC'},
{'ticker' : 'AGK.L', 'company' : 'Aggreko PLC'},
{'ticker' : 'AMEC.L', 'company' : 'AMEC PLC'},
{'ticker' : 'ANTO.L', 'company' : 'Antofagasta PLC'},
{'ticker' : 'ARM.L', 'company' : 'ARM Holdings PLC'},
{'ticker' : 'AV.L', 'company' : 'Aviva PLC'},
{'ticker' : 'AZN.L', 'company' : 'AstraZeneca PLC'},
{'ticker' : 'BA.L', 'company' : 'BAE Systems PLC'},
{'ticker' : 'BAB.L', 'company' : 'Babcock International Group PLC'},
{'ticker' : 'BARC.L', 'company' : 'Barclays PLC'},
{'ticker' : 'BATS.L', 'company' : 'British American Tobacco PLC'},
{'ticker' : 'BG.L', 'company' : 'BG Group PLC'},
{'ticker' : 'BLND.L', 'company' : 'British Land Co PLC'},
{'ticker' : 'BLT.L', 'company' : 'BHP Billiton PLC'},
{'ticker' : 'BNZL.L', 'company' : 'Bunzl PLC'},
{'ticker' : 'BP.L', 'company' : 'BP PLC'},
{'ticker' : 'BRBY.L', 'company' : 'Burberry Group PLC'},
{'ticker' : 'BSY.L', 'company' : 'British Sky Broadcasting Group PLC'},
{'ticker' : 'BT-A.L', 'company' : 'BT Group PLC'},
{'ticker' : 'CCL.L', 'company' : 'Carnival PLC'},
{'ticker' : 'CNA.L', 'company' : 'Centrica PLC'},
{'ticker' : 'CPG.L', 'company' : 'Compass Group PLC'},
{'ticker' : 'CPI.L', 'company' : 'Capita PLC'},
{'ticker' : 'CRDA.L', 'company' : 'Croda International PLC'},
{'ticker' : 'CRH.L', 'company' : 'CRH PLC'},
{'ticker' : 'CSCG.L', 'company' : 'Capital Shopping Centres Group PLC'},
{'ticker' : 'DGE.L', 'company' : 'Diageo PLC'},
{'ticker' : 'ENRC.L', 'company' : 'Eurasian Natural Resources Corporation PLC'},
{'ticker' : 'EVR.L', 'company' : 'EVRAZ'},
{'ticker' : 'EXPN.L', 'company' : 'Experian PLC'},
{'ticker' : 'FRES.L', 'company' : 'Fresnillo PLC'},
{'ticker' : 'GFS.L', 'company' : 'G4S PLC'},
{'ticker' : 'GKN.L', 'company' : 'GKN PLC'},
{'ticker' : 'GLEN.L', 'company' : 'GLENCORE INTL'},
{'ticker' : 'GSK.L', 'company' : 'GlaxoSmithKline PLC'},
{'ticker' : 'HL.L', 'company' : 'Hargreaves Lansdown PLC'},
{'ticker' : 'HMSO.L', 'company' : 'Hammerson PLC'},
{'ticker' : 'HSBA.L', 'company' : 'HSBC Holdings PLC'},
{'ticker' : 'IAG.L', 'company' : 'INTL. CONS. AIR GRP'},
{'ticker' : 'IHG.L', 'company' : 'InterContinental Hotels Group PLC'},
{'ticker' : 'IMI.L', 'company' : 'IMI PLC'},
{'ticker' : 'IMT.L', 'company' : 'Imperial Tobacco Group PLC'},
{'ticker' : 'ITRK.L', 'company' : 'Intertek Group PLC'},
{'ticker' : 'ITV.L', 'company' : 'ITV PLC'},
{'ticker' : 'JMAT.L', 'company' : 'Johnson Matthey PLC'},
{'ticker' : 'KAZ.L', 'company' : 'Kazakhmys PLC'},
{'ticker' : 'KGF.L', 'company' : 'Kingfisher PLC'},
{'ticker' : 'LAND.L', 'company' : 'Land Securities Group PLC'},
{'ticker' : 'LGEN.L', 'company' : 'Legal & General Group PLC'},
{'ticker' : 'LLOY.L', 'company' : 'Lloyds Banking Group PLC'},
{'ticker' : 'MGGT.L', 'company' : 'Meggitt PLC'},
{'ticker' : 'MKS.L', 'company' : 'Marks & Spencer Group PLC'},
{'ticker' : 'MRO.L', 'company' : 'Melrose PLC'},
{'ticker' : 'MRW.L', 'company' : 'Morrison (Wm) Supermarkets PLC'},
{'ticker' : 'NG.L', 'company' : 'National Grid PLC'},
{'ticker' : 'NXT.L', 'company' : 'Next PLC'},
{'ticker' : 'OML.L', 'company' : 'Old Mutual PLC'},
{'ticker' : 'PFC.L', 'company' : 'Petrofac Ltd'},
{'ticker' : 'PNN.L', 'company' : 'Pennon Group PLC'},
{'ticker' : 'POLY.L', 'company' : 'POLYMETAL INTL'},
{'ticker' : 'PRU.L', 'company' : 'Prudential PLC'},
{'ticker' : 'PSON.L', 'company' : 'Pearson PLC'},
{'ticker' : 'RB.L', 'company' : 'Reckitt Benckiser Group PLC'},
{'ticker' : 'RBS.L', 'company' : 'Royal Bank of Scotland Group PLC'},
{'ticker' : 'RDSA.L', 'company' : 'Royal Dutch Shell PLC'},
{'ticker' : 'RDSB.L', 'company' : 'Royal Dutch Shell PLC'},
{'ticker' : 'REL.L', 'company' : 'Reed Elsevier PLC'},
{'ticker' : 'REX.L', 'company' : 'REXAM PLC'},
{'ticker' : 'RIO.L', 'company' : 'Rio Tinto PLC'},
{'ticker' : 'RR.L', 'company' : 'Rolls-Royce Group PLC'},
{'ticker' : 'RRS.L', 'company' : 'Randgold Resources Ltd'},
{'ticker' : 'RSA.L', 'company' : 'RSA Insurance Group PLC'},
{'ticker' : 'RSL.L', 'company' : 'Resolution Ltd'},
{'ticker' : 'SAB.L', 'company' : 'SABMiller PLC'},
{'ticker' : 'SBRY.L', 'company' : 'Sainsbury (J) PLC'},
{'ticker' : 'SDR.L', 'company' : 'Schroders PLC'},
{'ticker' : 'SGE.L', 'company' : 'Sage Group (The) PLC'},
{'ticker' : 'SHP.L', 'company' : 'Shire PLC'},
{'ticker' : 'SL.L', 'company' : 'Standard Life PLC'},
{'ticker' : 'SMIN.L', 'company' : 'Smiths Group PLC'},
{'ticker' : 'SN.L', 'company' : 'Smith & Nephew PLC'},
{'ticker' : 'SRP.L', 'company' : 'Serco Group PLC'},
{'ticker' : 'SSE.L', 'company' : 'SSE PLC'},
{'ticker' : 'STAN.L', 'company' : 'Standard Chartered PLC'},
{'ticker' : 'SVT.L', 'company' : 'Severn Trent PLC'},
{'ticker' : 'TATE.L', 'company' : 'Tate & Lyle PLC'},
{'ticker' : 'TLW.L', 'company' : 'Tullow Oil PLC'},
{'ticker' : 'TSCO.L', 'company' : 'Tesco PLC'},
{'ticker' : 'ULVR.L', 'company' : 'Unilever PLC'},
{'ticker' : 'UU.L', 'company' : 'United Utilities Group PLC'},
{'ticker' : 'VED.L', 'company' : 'Vedanta Resources PLC'},
{'ticker' : 'VOD.L', 'company' : 'Vodafone Group PLC'},
{'ticker' : 'WEIR.L', 'company' : 'Weir Group PLC'},
{'ticker' : 'WG.L', 'company' : 'Wood Group (John) PLC'},
{'ticker' : 'WOS.L', 'company' : 'Wolseley PLC'},
{'ticker' : 'WPP.L', 'company' : 'WPP PLC'},
{'ticker' : 'WTB.L', 'company' : 'Whitbread PLC'},
{'ticker' : 'XTA.L', 'company' : 'Xstrata PLC'}]
